# This is based on the workflow example from https://github.com/erikmd/docker-coq-github-action-demo

name: CI

# Controls when the action will run:
# https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#filtering-for-specific-branches-tags-and-paths
# Triggers the workflow on push events for the master branch only,
# or all pull request events:
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - '**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# This workflow contains two jobs, build and mathcomp:
jobs:
  # The type of runner that the job will run on;
  # the OS must be GNU/Linux to be able to use the docker-coq-action
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - mathcomp/mathcomp:1.11.0-coq-8.11
          - mathcomp/mathcomp:1.11.0-coq-8.12
#          - mathcomp/mathcomp-dev:coq-dev
      max-parallel: 4
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          before_install: opam config list; opam repo list;
           opam list; opam pin add coq-mathcomp-finmap --dev-repo --no-action
          opam_file: './coq-event-struct.opam'
          custom_image: ${{ matrix.image }}

